### ISSUE TITLE
java.io.FileNotFoundException: ../helloworld/src/main/webapp

### ISSUE THREAD

**Issue by fagnercarvalho** [commit-conf/jetty-embedded#1]
I running both commands but I getting a FileNotFoundException. I doing something wrong?

```
:compileJava
:processResources UP-TO-DATE
:classes
:jetty
Listening for transport dt_socket at address: 5005
                                                   2014-11-22 20:11:50.582:INFO:
:main: Logging initialized @138ms
2014-11-22 20:11:50.732:INFO:oejs.Server:main: jetty-9.3.0.M1
2014-11-22 20:11:50.819:WARN:oejw.WebInfConfiguration:main: Web application not
found ../helloworld/src/main/webapp
2014-11-22 20:11:50.819:WARN:oejw.WebAppContext:main: Failed startup of context
o.e.j.w.WebAppContext@1aaf3cb{/helloworld,null,null}{../helloworld/src/main/weba
pp}
java.io.FileNotFoundException: ../helloworld/src/main/webapp
        at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfigurati
on.java:493)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfi
guration.java:72)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.jav
a:462)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:498
)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi
feCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand
ler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi
feCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:399)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand
ler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at com.extrema.jetty.embedded.JettyServer.main(JettyServer.java:45)
2014-11-22 20:11:50.822:WARN:oejuc.AbstractLifeCycle:main: FAILED o.e.j.w.WebApp
Context@1aaf3cb{/helloworld,null,UNAVAILABLE}{../helloworld/src/main/webapp}: ja
va.io.FileNotFoundException: ../helloworld/src/main/webapp
java.io.FileNotFoundException: ../helloworld/src/main/webapp
        at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfigurati
on.java:493)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfi
guration.java:72)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.jav
a:462)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:498
)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi
feCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand
ler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi
feCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:399)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand
ler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at com.extrema.jetty.embedded.JettyServer.main(JettyServer.java:45)
2014-11-22 20:11:50.823:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.je
tty.server.handler.HandlerCollection@6f531a15[o.e.j.w.WebAppContext@1aaf3cb{/hel
loworld,null,UNAVAILABLE}{../helloworld/src/main/webapp}]: java.io.FileNotFoundE
xception: ../helloworld/src/main/webapp
java.io.FileNotFoundException: ../helloworld/src/main/webapp
        at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfigurati
on.java:4                                                                      9
3)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfi
guration.java:72)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.jav
a:462)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:498
)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi
feCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand
ler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi
feCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:399)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand
ler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at com.extrema.jetty.embedded.JettyServer.main(JettyServer.java:45)
2014-11-22 20:11:50.854:INFO:oejs.ServerConnector:main: Started ServerConnector@
45051da4{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2014-11-22 20:11:50.855:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.je
tty.server.Server@52dd1d62: java.io.FileNotFoundException: ../helloworld/src/mai
n/webapp
java.io.FileNotFoundException: ../helloworld/src/main/webapp
        at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfigurati
on.java:493)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfi
guration.java:72)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.jav
a:462)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:498
)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
       .eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle
.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand
ler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi
feCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:399)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand
ler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at com.extrema.jetty.embedded.JettyServer.main(JettyServer.java:45)
Exception in thread "main" java.io.FileNotFoundException: ../helloworld/src/main
/webapp
        at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfigurati
on.java:493)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfi
guration.java:72)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.jav
a:462)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:498
)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi
feCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand
ler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi
feCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:399)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:114)
        at org.ecetty.server.handler.AbstractHandler.doStart(AbstractHandler.jav
a:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at com.extrema.jetty.embedded.JettyServer.main(JettyServer.java:45)
> Building 75% > :jetty
```

**Comment by AgnieszkaPajak** [comment]
I have the same problem :< I tried running all the build, war and other tasks available here but nothing. I really wish someone answered here :< You gave me hope I could finally write JavaEE on IntelliJ community and after a wasted hour I am back to square one :< Still, thanks for this, maybe I will look more into gradle.

**Comment by zhl2008** [comment]
create the folder called webapp will solve this problem

But when I visit the helloworld/foo , it  turns out to be 404 ,  and there is no class file in the helloworld project. what the f*ck
